name: Fill CCBot PR info

permissions:
    contents: write
    pull-requests: write

on:
    pull_request:
        types: [opened]

jobs:
    completePR:
        name: Fill CCBot PR info
        runs-on: ubuntu-latest
        if: startsWith(github.event.pull_request.title, 'CCBot')

        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.PAT }}
                  fetch-depth: 0

            # - uses: actions/checkout@v4
            #   with:
            #     ref: master-final

            # - uses: actions/setup-node@v4
            #   with:
            #       node-version: 20

            # - run: npm ci

            # - name: Checkout
            #   run: |
            #       git checkout ${{ github.head_ref }}

            - name: Update the database
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -e
                  echo "das" >> testfile.txt

            - name: Commit changes 
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
              run: |
                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
                  git add -A
                  git commit -m "CCBot: Fill '${ID}' info"

                  # git commit --allow-empty -m 'trigger the goddamn ci'

                  # git push

            - name: Push changes
              uses: 'ad-m/github-push-action@master'
              with:
                  github_token: ${{ secrets.PAT }}
                  branch: ${{ github.head_ref }}

            # - name: Push changes
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: |
            #       git push
