name: Fill CCBot PR info
on:
    pull_request:
        branches:
            - 'ccbot/**'
        types: [opened]

jobs:
    completePR:
        name: Fill CCBot PR info
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - working-directory: build/
              run: npm ci
            - name: Update the database
              working-directory: build/
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  OUT="$(npm run start)"
                  echo "$OUT"
                  OUT="$(echo "$OUT" | tail -1)"
                  echo "$OUT"
                  ID="$(echo "$OUT" | awk -F'|' '{print $1}')"
                  VERSION="$(echo "$OUT" | awk -F'|' '{print $2}')"
                  TITLE="$(echo "$OUT" | awk -F'|' '{print $3}')"
                  DESCRIPTION="$(echo "$OUT" | awk -F'|' '{print $4}')"

                  git config --global user.name "${GITHUB_ACTOR}"
                  git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
                  git commit --all -m "CCBot: Fill '${ID}' info"
                  git push

                  gh pr edit "${{ github.event.pull_request.number }}" --title "CCBot: ${ID}"
                  gh pr comment "${{ github.event.pull_request.number }}" --body "Mod info:<br>${ID} v${VERSION}<br>${DESCRIPTION}"
