name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
    check_database:
        name: Check database
        if: "!startsWith(github.event.pull_request.title, 'CCBot:')"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - working-directory: build/
              run: npm ci
            - name: npm run test
              working-directory: build/
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm test
